### ISSUE TITLE
ActiveRecord::MissingAttributeError: missing attribute: annotation

### ISSUE THREAD

**Issue by obrie** [pluginaweek/table_helper#1]
**closer** opened this issue

Hello,

I catched following exception:

 @@@
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body_row.rb:30:in `send&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body_row.rb:30:in`initialize&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body_row.rb:28:in `each&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body_row.rb:28:in`initialize&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body.rb:92:in `new&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body.rb:92:in`build_row&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body.rb:81:in `build&rsquo;
    /Library/Ruby/Gems/1.8/gems/activerecord-2.2.2/lib/active_record/base.rb:1907:in`each_with_index&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body.rb:80:in `each&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body.rb:80:in`each_with_index&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/body.rb:80:in `build&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper/collection_table.rb:41:in`build&rsquo;
    /Users/closer/Projects/test_table_helper/vendor/plugins/table_helper/lib/table_helper.rb:173:in `collection_table&rsquo;
    ./test/unit/post_test.rb:12:in`test_wrong_annotation_column&rsquo;
    /Library/Ruby/Gems/1.8/gems/activesupport-2.2.2/lib/active_support/testing/setup_and_teardown.rb:60:in `__send__&rsquo;
    /Library/Ruby/Gems/1.8/gems/activesupport-2.2.2/lib/active_support/testing/setup_and_teardown.rb:60:in`run&rsquo;

 @@@

because I excluded &rsquo;annotation&rsquo; column from SQL query.

You can reproduce error using attached file (run one unit-test).

Can you fix it?

Thanks

P.S.
  ruby 1.8.6 (2008-03-03 patchlevel 114) [universal-darwin9.0]
  Rails 2.2.2
  MAC OS 1.5.4

[original LH ticket](http://pluginaweek.lighthouseapp.com/projects/13290/tickets/1)

 This ticket has 1 attachment(s).

**Comment by obrie** [comment]
(from [b9e107d93ebc73d10a310ccd12401054057b822b]) Fix default headers including all model columns when using :select in the collection query [#1 state:resolved]
http://github.com/pluginaweek/table_helper/commit/b9e107d93ebc73d10a310ccd12401054057b822b

**Comment by obrie** [comment]
Thanks for the bug report!
